In [1]:
"""
Escrevendo o Passo a Passo do projeto!
    Primeiramente vamos tratar os dados...
        1º Obter o input com o numero do arquivo a ser lido.
        2º Importar os dados extraidos do SAJ em formato xlsx.
        3º Obter os parametros de formatação dos dados.
        4º Aplicar os padrões de formatação nos dados.
        5º Ordena-los em pagos e depois gratuitos.
        6º Exibir os dados tratados.
    Agora vamos construir o bot...
        7º Obter os ultimos parametros de execução.
        7º Abrir o navegador, inserir o login e solicitar a senha.
        8º Salvar os dados tratados em csv, carrega-los na memoria e iniciar a automação.

Instalando os pacotes no ubuntu através do terminal:
    sudo apt install python3-pandas python3-numpy python3-openpyxl python3-plotly
Instalando o Jupter:
    Nas extensões do VSCode instale e habilite o jupter
    E instale o kernel Jupyter também.
"""

'\nEscrevendo o Passo a Passo do projeto!\n    Primeiramente vamos tratar os dados...\n        1º Obter o input com o numero do arquivo a ser lido.\n        2º Importar os dados extraidos do SAJ em formato xlsx.\n        3º Obter os parametros de formatação dos dados.\n        4º Aplicar os padrões de formatação nos dados.\n        5º Ordena-los em pagos e depois gratuitos.\n        6º Exibir os dados tratados.\n    Agora vamos construir o bot...\n        7º Obter os ultimos parametros de execução.\n        7º Abrir o navegador, inserir o login e solicitar a senha.\n        8º Salvar os dados tratados em csv, carrega-los na memoria e iniciar a automação.\n\nInstalando os pacotes no ubuntu através do terminal:\n    sudo apt install python3-pandas python3-numpy python3-openpyxl python3-plotly\nInstalando o Jupter:\n    Nas extensões do VSCode instale e habilite o jupter\n    E instale o kernel Jupyter também.\n'

In [2]:
import os
import pandas as pd

print('Bem vindo Sogrão!')

Bem vindo Sogrão!

### 1º Obter o input com o numero do arquivo a ser lido.

In [3]:
# Lendo os arquivos presentes na pasta atual ignorando arquivos desnecessários
arquivos = [arq for arq in os.listdir() if not arq.endswith(('.ipynb', '.venv'))]
print("Arquivos disponíveis para processamento:")
for i, arq in enumerate(arquivos, start=1):
    print(f"{i}. {arq}")
saj = int(input("Digite o número do arquivo SAJ a ser processado: ")) - 1

Arquivos disponíveis para processamento:
1. .git
2. gratis.py
3. gratuito.py
4. pago.py
5. Relatorio.xlsx
6. xlsx

### 2º Importar os dados extraidos do SAJ em formato xlsx.

In [4]:
dados = pd.read_excel(arquivos[saj], engine='calamine', header=2) # usei header=2 para pular as 2 linhas iniciais
#print("Essa é a primeira linha do sua lista de dados:")
dados

,Processo,Mandado,Destinatário,Receb. oficial,Receb. central,Guia de Recolhimento,Forma de pagamento
0,1500255-50.2023.8.26.0559,576.2025/107925-6,MARIA VITÓRIA APARECIDA MESSIAS DA SILVA,11/12/2025 11:41:52,17/12/2025 12:19:30,Não,Justiça Gratuita
1,0003707-31.2011.8.26.0538,538.2025/005288-6,Joao Pereira de Freitas,04/12/2025 09:09:12,08/12/2025 09:24:31,Não,Justiça Gratuita
2,1025048-16.2024.8.26.0482,482.2025/049188-4,Andre Luis da Silva Garrido,30/10/2025 19:24:26,17/12/2025 09:00:16,Não,Justiça Paga
3,1500327-63.2019.8.26.0434,434.2025/005586-9,MAIKON DAVID RITA DE SOUSA,10/12/2025 11:35:16,17/12/2025 12:18:18,Não,Justiça Gratuita
4,1000700-44.2025.8.26.0434,434.2025/005488-9,Adriana Ribeiro Celestino,03/12/2025 11:34:16,08/12/2025 09:13:49,Não,Justiça Gratuita
...,...,...,...,...,...,...,...
162,1500107-55.2021.8.26.0544,108.2025/009637-4,DENIS SILVA DE OLIVEIRA,04/12/2025 09:16:03,17/12/2025 12:17:13,Não,Justiça Gratuita
163,1501123-06.2024.8.26.0070,070.2025/014036-8,Ana Carolina Cardoso,10/12/2025 11:27:34,17/12/2025 12:19:12,Não,Justiça Gratuita
164,1501371-69.2024.8.26.0070,070.2025/013428-7,ISAQUE ANDRÉ MOREIRA ALEIXO,27/11/2025 09:22:52,08/12/2025 09:26:09,Não,Justiça Gratuita
165,0027011-58.2017.8.26.0050,050.2025/281235-4,Eder Fernando de Lima,02/12/2025 11:08:39,08/12/2025 09:07:53,Não,Justiça Gratuita
166,1500433-80.2018.8.26.0621,028.2025/012819-1,DOUGLAS ANDERSON DE OLIVEIRA,10/12/2025 11:37:01,17/12/2025 12:14:48,Não,Justiça Gratuita

In [5]:
print("Essa é a primeira linha do sua lista de dados:")
print(dados.head(1))
# Verificando se os dados foram estão no formato esperado
try:
    # Verificando se existem exatamente 7 colunas
    assert len(dados.columns) == 7, "Número de colunas incorreto."
    # Verificando se os nomes das colunas estão corretos
    colunas_esperadas = ['Processo', 'Mandado', 'Destinatário', 'Receb. oficial', 'Receb. central', 'Guia de Recolhimento', 'Forma de pagamento']
    assert list(dados.columns) == colunas_esperadas, "Nomes das colunas incorretos."
except AssertionError:
    print("Erro: O arquivo selecionado não parece conter o padrão esperado do SAJ.")
    exit(1)
print(f'...\nDados carregados com sucesso num total de {len(dados)} linhas e {len(dados.columns)} colunas.')

Essa é a primeira linha do sua lista de dados:
                    Processo            Mandado  \
0  1500255-50.2023.8.26.0559  576.2025/107925-6

                               Destinatário       Receb. oficial  \
0  MARIA VITÓRIA APARECIDA MESSIAS DA SILVA  11/12/2025 11:41:52

        Receb. central Guia de Recolhimento Forma de pagamento
0  17/12/2025 12:19:30                  Não   Justiça Gratuita
...
Dados carregados com sucesso num total de 167 linhas e 7 colunas.

### 3º Obter os parametros de formatação dos dados.

In [6]:
# 1º Solicitando o mês para referência
meses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]
while True:
    mes_numero = input(f"Meses de referência...\n1 - Janeiro\n2 - Fevereiro\n3 - Março\n4 - Abril\n5 - Maio\n6 - Junho\n7 - Julho\n8 - Agosto\n9 - Setembro\n10 - Outubro\n11 - Novembro\n12 - Dezembro\nEntre apenas com o NÚMERO do mês desejado: ").strip()
    if mes_numero == "":
        pass
    if mes_numero in ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]: 
        mes_nome = meses[int(mes_numero) - 1]
        break
    print("Entrada inválida! Entre com um número de 1 a 12.")
print(f'Mês definido como: {mes_nome}')

# 2º Solicitando o valor da cota
cota = 111.06
while True:
    entrada_cota = input(f"Entre com o valor da cota atual. Ou apenas pressione ENTER para R${cota}: ").strip().replace(',', '.')
    if entrada_cota == "":
        break
    if entrada_cota.replace('.', '', 1).isdigit():
        valor_digitado = float(entrada_cota)
        if valor_digitado >= 0:
            cota = valor_digitado
            break
    else:
        print("Entrada inválida! Digite apenas números positivos, ponto ou vírgula.")
print(f'Valor da cota definido como: R${cota:.2f}')

# 3º Solicitando o valor do JG
JP = 1
while True:
    entrada_JP = input("Entre com 0 para o valor de JP. Ou apenas pressione ENTER para 1: ").strip()
    if entrada_JP == "":
        break
    if entrada_JP in ["0", "1"]:
        JP = int(entrada_JP)
        break
    print("Entrada inválida! Digite um número de 0 a 1.")
print(f'Número de JP definido como: {JP}')

# 4º Solicitando o valor de deslocamento
deslocamento = 'S'
while True:
    entrada_deslocamento = input("Entre com 'N' para o valor de deslocamento. Ou apenas pressione ENTER para 'S': ").strip().upper()
    if entrada_deslocamento == "":
        break
    elif entrada_deslocamento in ['N', 'S']:
        deslocamento = entrada_deslocamento
        break
    print("Entrada inválida! Entre com N ou S.")
print(f'Deslocamento definido como: {deslocamento}')

#robinsonp@tjsp.jus.br
#@.3461@BHc

# 5º Solicitando o tempo de pausa
pausa = 2
while True:
    entrada_pausa = input("Entre com o tempo de pausa em segundos. Ou apenas pressione ENTER para 2 segundos: ").strip().replace(',', '.')
    if entrada_pausa == "":
        break
    if entrada_pausa.replace('.', '', 1).isdigit():
        pausa_digitada = float(entrada_pausa)
        if pausa_digitada >= 0:
            pausa = pausa_digitada
            break
    else:
        print("Entrada inválida! Digite apenas números positivos, ponto ou vírgula.")
print(f'Tempo de pausa definido como: {pausa} segundos')

Mês definido como: Janeiro
Valor da cota definido como: R$111.06
Número de JP definido como: 1
Deslocamento definido como: S
Tempo de pausa definido como: 2 segundos

### 4º Aplicar os padrões de formatação nos dados.

In [9]:
import pandas as pd

tratados = pd.DataFrame(
    columns=['PROCESSO', 'MANDADO', 'DESTINATÁRIO', 'RECEB. OFICIAL', 'RECEB. CENTRAL', 'N.GRD', 'FORMA PAGAMENTO', 'VALOR', 'COTA', 'DESLOCAMENTO', 'REGRA ESPECIAL', 'CONTROLE']
).astype('string')

# Setando dados na coluna 'PROCESSO'
tratados['PROCESSO'] = (
    dados['Processo']
    .astype(str)                  # Garante que é string para manipular
    .str.replace(r'\D', '', regex=True) # Remove TUDO que não for número (ponto, traço, espaço)
    .str.zfill(20)                # Preenche com 0 à esquerda até completar 20
)

# Setando dados na coluna 'MANDADO'
def formatar_mandado(numero):
    """Formata 14 dígitos para formato CNJ: 123.4567/890123-4"""
    string = str(numero).replace('.', '').replace('-', '').replace('/', '').strip()
    if len(string) == 14:
        return f"{string[:3]}.{string[3:7]}/{string[7:13]}-{string[13:]}"
    return string
tratados['MANDADO'] = dados['Mandado'].apply(formatar_mandado)

# Setando dados na coluna 'DESTINATÁRIO'
tratados['DESTINATÁRIO'] = (dados['Destinatário'].astype(str).str.strip().str.upper())

# Setando dados na coluna 'RECEB. OFICIAL'
tratados['RECEB. OFICIAL'] = (pd.to_datetime(dados['Receb. oficial'], dayfirst=True).dt.strftime('%d/%m/%Y').astype('string'))

# Setando dados na coluna 'RECEB. CENTRAL'
tratados['RECEB. CENTRAL'] = (pd.to_datetime(dados['Receb. central'], dayfirst=True).dt.strftime('%d/%m/%Y').astype('string'))

# Setando dados na coluna 'N.GRD'
tratados['N.GRD'] = dados['Guia de Recolhimento'].astype('string').str.strip()

# Setando dados na coluna 'FORMA PAGAMENTO'
tratados['FORMA PAGAMENTO'] = (dados['Forma de pagamento'].map({'Gratuito': 'JUSTIÇA GRATUITA'}).fillna('JUSTIÇA PAGA').astype('string').str.strip())

# Setando dados na coluna 'VALOR'
tratados['VALOR'] = tratados['FORMA PAGAMENTO'].map({'JUSTIÇA GRATUITA': '0,00','JUSTIÇA PAGA': f"{float(cota):.2f}".replace('.', ',')}).fillna(f"{float(cota):.2f}".replace('.', ',')).astype('string')

# Setando dados na coluna 'COTA'
tratados['COTA'] = str(int(JP))

# Setando dados na coluna 'DESLOCAMENTO'
tratados['DESLOCAMENTO'] = deslocamento

# Setando dados na coluna 'COTA'
tratados['REGRA ESPECIAL'] = 'N'

# Setando dados na coluna 'COTA'
tratados['CONTROLE'] = 'N'

# Setando dados na coluna 'COTA'
tratados['CONFERE'] = 'O'

tratados

,PROCESSO,MANDADO,DESTINATÁRIO,RECEB. OFICIAL,RECEB. CENTRAL,N.GRD,FORMA PAGAMENTO,VALOR,COTA,DESLOCAMENTO,REGRA ESPECIAL,CONTROLE,CONFERE
0,15002555020238260559,576.2025/107925-6,MARIA VITÓRIA APARECIDA MESSIAS DA SILVA,11/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
1,00037073120118260538,538.2025/005288-6,JOAO PEREIRA DE FREITAS,04/12/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
2,10250481620248260482,482.2025/049188-4,ANDRE LUIS DA SILVA GARRIDO,30/10/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
3,15003276320198260434,434.2025/005586-9,MAIKON DAVID RITA DE SOUSA,10/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
4,10007004420258260434,434.2025/005488-9,ADRIANA RIBEIRO CELESTINO,03/12/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,15001075520218260544,108.2025/009637-4,DENIS SILVA DE OLIVEIRA,04/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
163,15011230620248260070,070.2025/014036-8,ANA CAROLINA CARDOSO,10/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
164,15013716920248260070,070.2025/013428-7,ISAQUE ANDRÉ MOREIRA ALEIXO,27/11/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
165,00270115820178260050,050.2025/281235-4,EDER FERNANDO DE LIMA,02/12/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
166,15004338020188260621,028.2025/012819-1,DOUGLAS ANDERSON DE OLIVEIRA,10/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O

In [10]:
# Salvando o arquivo tratado em xlsx com o nome da variável mes_nome
nome_arquivo = f'Dados_Tratados_{mes_nome}.xlsx'
tratados.to_excel(nome_arquivo, index=False)
print(f'Arquivo salvo com sucesso como: {nome_arquivo}')

Arquivo salvo com sucesso como: Dados_Tratados_Janeiro.xlsx

In [11]:
tratados

,PROCESSO,MANDADO,DESTINATÁRIO,RECEB. OFICIAL,RECEB. CENTRAL,N.GRD,FORMA PAGAMENTO,VALOR,COTA,DESLOCAMENTO,REGRA ESPECIAL,CONTROLE,CONFERE
0,15002555020238260559,576.2025/107925-6,MARIA VITÓRIA APARECIDA MESSIAS DA SILVA,11/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
1,00037073120118260538,538.2025/005288-6,JOAO PEREIRA DE FREITAS,04/12/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
2,10250481620248260482,482.2025/049188-4,ANDRE LUIS DA SILVA GARRIDO,30/10/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
3,15003276320198260434,434.2025/005586-9,MAIKON DAVID RITA DE SOUSA,10/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
4,10007004420258260434,434.2025/005488-9,ADRIANA RIBEIRO CELESTINO,03/12/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,15001075520218260544,108.2025/009637-4,DENIS SILVA DE OLIVEIRA,04/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
163,15011230620248260070,070.2025/014036-8,ANA CAROLINA CARDOSO,10/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
164,15013716920248260070,070.2025/013428-7,ISAQUE ANDRÉ MOREIRA ALEIXO,27/11/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
165,00270115820178260050,050.2025/281235-4,EDER FERNANDO DE LIMA,02/12/2025,08/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O
166,15004338020188260621,028.2025/012819-1,DOUGLAS ANDERSON DE OLIVEIRA,10/12/2025,17/12/2025,Não,JUSTIÇA PAGA,"111,06",1,S,N,N,O